### ISSUE TITLE
Undefine Video and Memory info. macOS Sierra.

### ISSUE THREAD

**Issue by carrolcox** [OCSInventory-NG/UnixAgent#92]
### General informations
Operating system :  Apple macOS Sierra (10.12.6)
Perl version : 5.18

### OCS Inventory informations
Unix agent version : Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3.1

### Problem's description
Regression error after update from 2.1.1 to 2.3.1
```
[Thu Nov  9 10:40:50 2017][debug] Failed to load Ocsinventory::Agent::Backend::OS::MacOS::Video: Can't locate Parse/EDID.pm in @INC (you may need to install the Parse::EDID module) (@INC contains: /Applications/OCSNG.app/Contents/Resources//lib/ /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Backend/OS/MacOS/Video.pm line 4.
BEGIN failed--compilation aborted at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Backend/OS/MacOS/Video.pm line 4.
Compilation failed in require at (eval 90) line 1.
BEGIN failed--compilation aborted at (eval 90) line 1.
```
and
```
[Thu Nov  9 10:40:50 2017][debug] runWithTimeout(): unexpected error: Undefined subroutine &Ocsinventory::Agent::Backend::OS::MacOS::Mem::can_load called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Backend/OS/MacOS/Mem.pm line 6.
[Thu Nov  9 10:40:50 2017][debug] Ocsinventory::Agent::Backend::OS::MacOS::Mem ignored

```

**Comment by carrolcox** [comment]
Perl detaled:
```
$ perl -V
Summary of my perl5 (revision 5 version 18 subversion 2) configuration:

  Platform:
    osname=darwin, osvers=16.0, archname=darwin-thread-multi-2level
    uname='darwin osx320.apple.com 16.0 darwin kernel version 15.0.0: wed jun 22 17:57:08 pdt 2016; root:xnu-3247.1.106.2.9~1development_x86_64 x86_64 '
    config_args='-ds -e -Dprefix=/usr -Dccflags=-g  -pipe  -Dldflags= -Dman3ext=3pm -Duseithreads -Duseshrplib -Dinc_version_list=none -Dcc=cc'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    useperlio=define, d_sfio=undef, uselargefiles=define, usesocks=undef
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='cc', ccflags ='-arch x86_64 -arch i386 -g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector',
    optimize='-Os',
    cppflags='-g -pipe -fno-common -DPERL_DARWIN -fno-strict-aliasing -fstack-protector'
    ccversion='', gccversion='4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='cc -mmacosx-version-min=10.12.5', ldflags ='-arch x86_64 -arch i386 -fstack-protector'
    libpth=/usr/lib /usr/local/lib
    libs=
    perllibs=
    libc=, so=dylib, useshrplib=true, libperl=libperl.dylib
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=bundle, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags='-arch x86_64 -arch i386 -bundle -undefined dynamic_lookup -fstack-protector'


Characteristics of this binary (from libperl):
  Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                        PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_MALLOC_WRAP
                        PERL_PRESERVE_IVUV PERL_SAWAMPERSAND USE_64_BIT_ALL
                        USE_64_BIT_INT USE_ITHREADS USE_LARGE_FILES
                        USE_LOCALE USE_LOCALE_COLLATE USE_LOCALE_CTYPE
                        USE_LOCALE_NUMERIC USE_PERLIO USE_PERL_ATOF
                        USE_REENTRANT_API
  Locally applied patches:
        /Library/Perl/Updates/<version> comes before system perl directories
        installprivlib and installarchlib points to the Updates directory
  Built under darwin
  Compiled at Feb  6 2017 22:16:22
  @INC:
    /Library/Perl/5.18/darwin-thread-multi-2level
    /Library/Perl/5.18
    /Network/Library/Perl/5.18/darwin-thread-multi-2level
    /Network/Library/Perl/5.18
    /Library/Perl/Updates/5.18.2
    /System/Library/Perl/5.18/darwin-thread-multi-2level
    /System/Library/Perl/5.18
    /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level
    /System/Library/Perl/Extras/5.18
```

**Comment by fbomj** [comment]
Hi,
As you use the Unix agent you have to install Parse::EDID perl module. This is not shipped with the agent. 
Regards
Frank

**Comment by carrolcox** [comment]
IMHO, Agent could contain Parse::EDID

**Comment by carrolcox** [comment]
Anywere 
second issue not resolved after manual installation Parse::EDID

**Comment by carrolcox** [comment]
@gillesdubois please help
